// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Dec 06 17:37:10 2021

IC_74LS245BA_RTL IC_74LS245BA_RTL_inst
(
	.bOE(bOE_sig) ,	// input  bOE_sig
	.B1(B1_sig) ,	// input  B1_sig
	.B2(B2_sig) ,	// input  B2_sig
	.B3(B3_sig) ,	// input  B3_sig
	.B4(B4_sig) ,	// input  B4_sig
	.B5(B5_sig) ,	// input  B5_sig
	.B6(B6_sig) ,	// input  B6_sig
	.B7(B7_sig) ,	// input  B7_sig
	.B8(B8_sig) ,	// input  B8_sig
	.A1(A1_sig) ,	// output  A1_sig
	.A2(A2_sig) ,	// output  A2_sig
	.A3(A3_sig) ,	// output  A3_sig
	.A4(A4_sig) ,	// output  A4_sig
	.A5(A5_sig) ,	// output  A5_sig
	.A6(A6_sig) ,	// output  A6_sig
	.A7(A7_sig) ,	// output  A7_sig
	.A8(A8_sig) 	// output  A8_sig
);

