// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Fri Oct 29 22:55:10 2021

IC_74LS161_RTL IC_74LS161_RTL_inst
(
	.bLOAD(bLOAD_sig) ,		// input  bLOAD_sig
	.bCLR(bCLR_sig) ,			// input  bCLR_sig
	.DATA_A(DATA_A_sig) ,	// input  DATA_A_sig
	.DATA_B(DATA_B_sig) ,	// input  DATA_B_sig
	.CLK(CLK_sig) ,			// input  CLK_sig
	.DATA_C(DATA_C_sig) ,	// input  DATA_C_sig
	.DATA_D(DATA_D_sig) ,	// input  DATA_D_sig
	.ENP(ENP_sig) ,			// input  ENP_sig
	.ENT(ENT_sig) ,			// input  ENT_sig
	.Q_A(Q_A_sig) ,			// output  Q_A_sig
	.Q_B(Q_B_sig) ,			// output  Q_B_sig
	.Q_C(Q_C_sig) ,			// output  Q_C_sig
	.Q_D(Q_D_sig) ,			// output  Q_D_sig
	.RCO(RCO_sig) 				// output  RCO_sig
);

