// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Tue Jan 11 14:26:00 2022

BE_8_BIT_Computer BE_8_BIT_Computer_inst
(
	.FPGA_CLK_SOURCE(FPGA_CLK_SOURCE_sig) ,	// input  FPGA_CLK_SOURCE_sig
	.CLK_SELECT(CLK_SELECT_sig) ,	// input  CLK_SELECT_sig
	.CLK_STEP(CLK_STEP_sig) ,	// input  CLK_STEP_sig
	.CLK_DIVIDER (CLK_DIVIDER _sig) ,	// input [2:0] CLK_DIVIDER _sig
	.CLR(CLR_sig) ,	// input  CLR_sig
	.DISPLAY_SELECT (DISPLAY_SELECT _sig) ,	// input [3:0] DISPLAY_SELECT _sig
	.TWOS_COMPLEMENT(TWOS_COMPLEMENT_sig) ,	// input  TWOS_COMPLEMENT_sig
	.HEXADECIMAL_FLAG(HEXADECIMAL_FLAG_sig) ,	// input  HEXADECIMAL_FLAG_sig
	.LED (LED _sig) ,	// output [7:0] LED _sig
	.SEVEN_SEG_0 (SEVEN_SEG_0 _sig) ,	// output [7:0] SEVEN_SEG_0 _sig
	.SEVEN_SEG_1 (SEVEN_SEG_1 _sig) ,	// output [7:0] SEVEN_SEG_1 _sig
	.SEVEN_SEG_2 (SEVEN_SEG_2 _sig) ,	// output [7:0] SEVEN_SEG_2 _sig
	.SEVEN_SEG_3 (SEVEN_SEG_3 _sig) ,	// output [7:0] SEVEN_SEG_3 _sig
	.SEVEN_SEG_4 (SEVEN_SEG_4 _sig) ,	// output [7:0] SEVEN_SEG_4 _sig
	.SEVEN_SEG_5 (SEVEN_SEG_5 _sig) ,	// output [7:0] SEVEN_SEG_5 _sig
	.HLT_LED(HLT_LED_sig) ,	// output  HLT_LED_sig
	.CLK_LED(CLK_LED_sig) 	// output  CLK_LED_sig
);

