// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Sat Nov 06 15:43:27 2021

IC_74LS283_RTL IC_74LS283_RTL_inst
(
	.B4(B4_sig) ,	// input  B4_sig
	.A4(A4_sig) ,	// input  A4_sig
	.B3(B3_sig) ,	// input  B3_sig
	.A3(A3_sig) ,	// input  A3_sig
	.B2(B2_sig) ,	// input  B2_sig
	.A2(A2_sig) ,	// input  A2_sig
	.B1(B1_sig) ,	// input  B1_sig
	.A1(A1_sig) ,	// input  A1_sig
	.C_IN(C_IN_sig) ,	// input  C_IN_sig
	.C_OUT(C_OUT_sig) ,	// output  C_OUT_sig
	.SUM_4(SUM_4_sig) ,	// output  SUM_4_sig
	.SUM_3(SUM_3_sig) ,	// output  SUM_3_sig
	.SUM_2(SUM_2_sig) ,	// output  SUM_2_sig
	.SUM_1(SUM_1_sig) 	// output  SUM_1_sig
);

