// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Wed Dec 08 20:01:48 2021

A_Register A_Register_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.CLR(CLR_sig) ,	// input  CLR_sig
	.A_REG_IN(A_REG_IN_sig) ,	// input [7:0] A_REG_IN_sig
	.A_REG_IN_EN(A_REG_IN_EN_sig) ,	// input  A_REG_IN_EN_sig
	.A_REG_OUT_EN(A_REG_OUT_EN_sig) ,	// input  A_REG_OUT_EN_sig
	.A_REG_DISPLAY(A_REG_DISPLAY_sig) ,	// output [7:0] A_REG_DISPLAY_sig
	.A_REG_ALU(A_REG_ALU_sig) ,	// output [7:0] A_REG_ALU_sig
	.A_REG_OUT_DB(A_REG_OUT_DB_sig) 	// output [7:0] A_REG_OUT_DB_sig
);

