// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Dec 06 17:53:09 2021

ALU ALU_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.SUBTRACT(SUBTRACT_sig) ,	// input  SUBTRACT_sig
	.A_REGISTER_IN(A_REGISTER_IN_sig) ,	// input [7:0] A_REGISTER_IN_sig
	.B_REGISTER_IN(B_REGISTER_IN_sig) ,	// input [7:0] B_REGISTER_IN_sig
	.ALU_OUT(ALU_OUT_sig) ,	// input  ALU_OUT_sig
	.ALU_FLAGS_OUT(ALU_FLAGS_OUT_sig) ,	// input  ALU_FLAGS_OUT_sig
	.ALU_DISPLAY(ALU_DISPLAY_sig) ,	// output [7:0] ALU_DISPLAY_sig
	.ALU_DB(ALU_DB_sig) ,	// output [7:0] ALU_DB_sig
	.CPU_Flags(CPU_Flags_sig) 	// output [7:0] CPU_Flags_sig
);

