// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Wed Dec 08 12:07:40 2021

Memory_Address_Register Memory_Address_Register_inst
(
	.CLR(CLR_sig) ,	// input  CLR_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.ADDRESS_BUS(ADDRESS_BUS_sig) ,	// input [7:0] ADDRESS_BUS_sig
	.MEMORY_ADDRESS_IN(MEMORY_ADDRESS_IN_sig) ,	// input  MEMORY_ADDRESS_IN_sig
	.MEMORY_ADDRESS_ENABLE(MEMORY_ADDRESS_ENABLE_sig) ,	// input  MEMORY_ADDRESS_ENABLE_sig
	.MEMORY_ADDRESS_OUT(MEMORY_ADDRESS_OUT_sig) ,	// output [3:0] MEMORY_ADDRESS_OUT_sig
	.MEMORY_ADDRESS_DISP(MEMORY_ADDRESS_DISP_sig) 	// output [3:0] MEMORY_ADDRESS_DISP_sig
);

