// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Dec 06 18:36:24 2021

Instruction_Register Instruction_Register_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.CLR(CLR_sig) ,	// input  CLR_sig
	.INST_REG_OUT(INST_REG_OUT_sig) ,	// input  INST_REG_OUT_sig
	.INST_REG_IN(INST_REG_IN_sig) ,	// input  INST_REG_IN_sig
	.INST_REG_IN_DB(INST_REG_IN_DB_sig) ,	// input [7:0] INST_REG_IN_DB_sig
	.INST_REG_DISPLAY(INST_REG_DISPLAY_sig) ,	// output [7:0] INST_REG_DISPLAY_sig
	.INST_OPCODE(INST_OPCODE_sig) ,	// output [3:0] INST_OPCODE_sig
	.INST_OPERAND(INST_OPERAND_sig) ,	// output [3:0] INST_OPERAND_sig
	.INST_REG_OUT_DB(INST_REG_OUT_DB_sig) 	// output [7:0] INST_REG_OUT_DB_sig
);

