// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Nov 04 23:15:51 2021

IC_74LS173_RTL IC_74LS173_RTL_inst
(
	.bG1(bG1_sig) ,	// input  bG1_sig
	.bG2(bG2_sig) ,	// input  bG2_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.CLR(CLR_sig) ,	// input  CLR_sig
	.D_1(D_1_sig) ,	// input  D_1_sig
	.D_2(D_2_sig) ,	// input  D_2_sig
	.D_3(D_3_sig) ,	// input  D_3_sig
	.D_4(D_4_sig) ,	// input  D_4_sig
	.bM(bM_sig) ,	// input  bM_sig
	.bN(bN_sig) ,	// input  bN_sig
	.Q_1(Q_1_sig) ,	// output  Q_1_sig
	.Q_2(Q_2_sig) ,	// output  Q_2_sig
	.Q_3(Q_3_sig) ,	// output  Q_3_sig
	.Q_4(Q_4_sig) 	// output  Q_4_sig
);

