// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Thu Dec 09 22:49:32 2021

Program_Counter Program_Counter_inst
(
	.CE(CE_sig) ,	// input  CE_sig
	.CLK(CLK_sig) ,	// input  CLK_sig
	.JMP(JMP_sig) ,	// input  JMP_sig
	.CLR(CLR_sig) ,	// input  CLR_sig
	.COUNT_OUT(COUNT_OUT_sig) ,	// input  COUNT_OUT_sig
	.PC_IN_DB(PC_IN_DB_sig) ,	// input [7:0] PC_IN_DB_sig
	.PC_DISP(PC_DISP_sig) ,	// output [3:0] PC_DISP_sig
	.PC_OUT_DB(PC_OUT_DB_sig) 	// output [7:0] PC_OUT_DB_sig
);

