// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Nov 22 19:37:10 2021

BE_Clock BE_Clock_inst
(
	.iCLK(iCLK_sig) ,	// input  iCLK_sig
	.CLK_SELECT(CLK_SELECT_sig) ,	// input  CLK_SELECT_sig
	.CLK_STEP(CLK_STEP_sig) ,	// input  CLK_STEP_sig
	.HLT(HLT_sig) ,	// input  HLT_sig
	.PGM_ENABLE(PGM_ENABLE_sig) ,	// input  PGM_ENABLE_sig
	.DIV_CLK(DIV_CLK_sig) ,	// input [2:0] DIV_CLK_sig
	.CLK(CLK_sig) ,	// output  CLK_sig
	.NOT_CLK(NOT_CLK_sig) ,	// output  NOT_CLK_sig
	.PGM_CLK(PGM_CLK_sig) ,	// output  PGM_CLK_sig
	.DISPLAY_CLK(DISPLAY_CLK_sig) 	// output  DISPLAY_CLK_sig
);

