// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon Nov 29 12:07:55 2021

RAM RAM_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.PGM_CLK(PGM_CLK_sig) ,	// input  PGM_CLK_sig
	.Read_Enable(Read_Enable_sig) ,	// input  Read_Enable_sig
	.Write_Enable(Write_Enable_sig) ,	// input  Write_Enable_sig
	.Address(Address_sig) ,	// input [3:0] Address_sig
	.Data_In(Data_In_sig) ,	// input [7:0] Data_In_sig
	.Data_Out_DB(Data_Out_DB_sig) ,	// output [7:0] Data_Out_DB_sig
	.Data_Out_DISP(Data_Out_DISP_sig) 	// output [7:0] Data_Out_DISP_sig
);

